version: "3.9"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    command: ["air", "-c", ".air.toml"]
