version: "3.8"

services:
  go:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=first
    volumes:
      - .:/app
    command: ["air"]
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.29
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: first
    volumes:
      - db-vol:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-vol:
